language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
install:
  - sudo apt-get update
  - sudo apt-get install -y -q rpm
  - mvn install -Ppackage -DskipUTs -DskipITs
script:
  - mvn test -Ptravis-test
  - mvn package -Ppackage -DskipUTs -DskipITs
