language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
install:
  - pushd stratio-ingestion-dist
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - popd
script:
  - mvn test -Ptravis-test
  - pushd stratio-ingestion-dist
  - mvn package -DskipTests
  - popd
