language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.m2
install:
  - cd stratio-ingestion-dist
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - cd stratio-ingestion-dist
  - mvn test -Ptravis-test
  - mvn package -DskipTests
